version: "3.4"
services:
    web:
        image: 'ghcr.io/chemistry/ui.crystallography.io:latest'
        restart: always
        build:
            context: ./
            dockerfile: Dockerfile
        networks:
          - net
          - traefik-public
        env_file:
          - ./.env
        environment:
          - PORT=8060
        deploy:
            update_config:
                order: start-first
                failure_action: rollback
                delay: 10s
            labels:
                - traefik.enable=true
                - traefik.docker.network=traefik-public
                - traefik.constraint-label=traefik-public
                - traefik.http.routers.web-http.rule=Host(`ui.crystallography.io`)
                - traefik.http.routers.web-http.entrypoints=http
                - traefik.http.routers.web-http.middlewares=https-redirect
                - traefik.http.routers.web-https.priority=10
                - traefik.http.routers.web-https.rule=Host(`ui.crystallography.io`)
                - traefik.http.routers.web-https.entrypoints=https
                - traefik.http.routers.web-https.tls=true
                - traefik.http.routers.web-https.tls.certresolver=le
                - traefik.http.services.web.loadbalancer.server.port=8060

networks:
  net:
  traefik-public:
    external: true

